# Generated by Django 2.2.4 on 2019-08-18 07:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0007_claim_stat'),
    ]

    operations = [
        migrations.RenameField(
            model_name='claim',
            old_name='Imya',
            new_name='name',
        ),
    ]
